server.port: 8082

spring:
  application:
    name: jpa-locking
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

#logging:
#  level:
#    org.hibernate:
#      SQL: DEBUG
#      type.descriptor.sql.BasicBinder: TRACE

---
spring:
  config:
    activate.on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/studiesdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: secret

---
spring:
  config:
    activate.on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/studiesdb
    username: postgres
    password: postgres

---
spring:
  config:
    activate.on-profile: mysql-test
  datasource:
    url:      # \
    username: #  ) they will be set dynamically by AbstractTestcontainers
    password: # /

---
spring:
  config:
    activate.on-profile: postgres-test
  datasource:
    url:      # \
    username: #  ) they will be set dynamically by AbstractTestcontainers
    password: # /
