server.port: 8085

spring:
  application:
    name: consumer
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/studiesdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: secret
